name: budget_app
description: A personal budgeting app

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.18.1  # Can now use latest version
  fluttertoast: ^8.2.2
  fl_chart: ^0.66.0  # Updated to latest compatible version
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/